# Generated by Django 5.0 on 2024-03-26 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myrecipe', '0005_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='recipe',
        ),
    ]
